# Generated by Django 5.0.6 on 2024-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default='source:', max_length=200),
            preserve_default=False,
        ),
    ]
